name: py38_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
    - ipykernel
    - openai==1.25.1 # ==0.27.8
    - azureml-rag[faiss]==0.2.30.2 # >=0.1.11
    - promptflow[azure]==1.5.0 # >=1.2.0 
    - promptflow-tools==1.4.0 # ==0.1.0.b5
    - promptflow-vectordb==0.2.10 # ==0.1.2
    - azure-ai-ml==1.15.0
    - azure-cli==2.60.0
    - azureml-core==1.56.0
    - keyring>=4.1.1
    - keyrings.alt
    - pytest>=2.2.3
    - pymongo

    # Pinned dependencies
    - azureml-inference-server-http


