name: py38_env
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8
  - pip
  - pip:
    - ipykernel
    - openai # ==0.27.8
    - azureml-rag[faiss] # >=0.1.11
    - promptflow[azure] # >=1.2.0 
    - promptflow-tools # ==0.1.0.b5
    - promptflow-vectordb # ==0.1.2
    - azure-ai-ml
    - azure-cli
    - azureml-core
    - keyring>=4.1.1
    - keyrings.alt
    - pytest>=2.2.3
    - pymongo

    # Pinned dependencies
    - azureml-inference-server-http


